### ISSUE TITLE
Repository rename

### ISSUE THREAD

**Issue by Samisafool** [AfoninZ/UltimMC#110]
@AfoninZ rename it thx

Or maybe someone can fork it and rename?

**Comment by Samisafool** [comment]
Can also make an org

**Comment by JulekSTN** [comment]
yeah, the best option is to change the repo name to UltimMC, cause that is the name that is used inside the launcher. also, multimc declared that using their name is wrong cause of the license.

**Comment by Samisafool** [comment]
:eyes: https://github.com/AfoninZ/MultiMC5-Cracked/commit/18aa0d2faafbfeb30671f8e3d81ec6427ad6f0f5

@AfoninZ is back!!! I guess this can have some progress now.
