### ISSUE TITLE
Microsoft Account option greyed out

### ISSUE THREAD

**Issue by RaXorX** [AfoninZ/UltimMC#119]
### Description of bug

Sorry, not a bug but a question. Is microsoft account option going to be implemented in the cracked version since I saw that it's been up and running in the official launcher. Was just wondering, didn't see any much specific mention regarding it here. If it'll be in the realms of the cracked or not. 

### Steps to reproduce

None

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
It actually could be implemented by putting the Azure API key, however isn't actually necessary, since this isn't the point of this fork.

**Comment by RaXorX** [comment]
Wait though, I mean I understand that's not the point but I was specifically talking about the account. Will checking for a valid MS account make it also check whether one has bought minecraft or not?

**Comment by Sebastian-byte** [comment]
> Wait though, I mean I understand that's not the point but I was specifically talking about the account. Will checking for a valid MS account make it also check whether one has bought minecraft or not?

Yes, it should work the same as it would in the vainilla upstream launcher.

**Comment by 64-Tesseract** [comment]
Any timeline for when MS logins could be implemented? Rather not have to use multiple versions of the same thing

**Comment by Sebastian-byte** [comment]
Think of UltimMC solely as a local version of the launcher, and the upstream as an online one.

**Comment by mhmatthewhugley** [comment]
> Think of UltimMC solely as a local version of the launcher, and the upstream as an online one.

That is a shame was hopping I finally found a open source launcher that had both offline accounts and online microsoft accounts. I personally think it would not be a lot of work to more closely maintain the same features the upstream has cause then you dont have to remove that code and after every update make sure you dont implement anything that uses the code which does not exist in this version.
