### ISSUE TITLE
Directory not found error while extracting mmc-crackedlin64.zip

### ISSUE THREAD

**Issue by LionCat3125** [AfoninZ/UltimMC#120]
### Operating System

Linux

### Description of bug

I extracted mmc-crackedlin64.zip file and it gives me this error
"Error opening file home/myusername/Documents/folder/mmc-crackedlin64/UltimMC/bin": Not a Directory

### Steps to reproduce

*Right clicked the zip file
*Clicked extract button
*Gives me the error

### Suspected cause

_What???_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
Unable to reproduce, try newer versions.
