### ISSUE TITLE
Linux ARM64 Support

### ISSUE THREAD

**Issue by MegaTKC** [AfoninZ/UltimMC#128]
### Operating System

Linux

### Description of bug

/home/username/MultiMC/src/launcher/minecraft/launch/InjectAuthlib.cpp:5:10: fatal error: Env.h: No such file or directory
    5 | #include <Env.h>

Everything just gets terminated after, 51%.

### Steps to reproduce

If you run `make -j4 install` since the Raspberry Pi 4 has 4 cores, it runs up until 51%.

### Suspected cause

I suspect that ARM is causing this bug, I can run multimc official without errors, but with this setup, I can't run multimc-cracked at all.

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
This is a known bug, build fails currently, go to the source folder and run `git reset --hard 66bb7105db93e0977bb64a59a12b001f780e0566`

**Comment by MegaTKC** [comment]
> This is a known bug, build fails currently, go to the source folder and run `git reset --hard 66bb7105db93e0977bb64a59a12b001f780e0566`

Hi, thanks for helping me above with this fix. How can I run Minecraft Now? I tried 1.8.9 and 1.8, but it shows this error.

1.0:
UltimMC version: 0.6.13-custom


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.226.199.74]

session.minecraft.net resolves to:
    [3.211.245.5, 52.70.238.65, 23.23.220.104]

textures.minecraft.net resolves to:
    [13.226.237.106, 13.226.237.16, 13.226.237.116, 13.226.237.8]

api.mojang.com resolves to:
    [13.226.234.211]


Minecraft folder is:
/home/username/MultiMC/install/instances/1.0/.minecraft


Java path is:
/usr/bin/java


Checking Java version...
Java is version 1.8.0_302, using 32-bit architecture, from Private Build.


Main Class:
  

Native path:
  /home/username/MultiMC/install/instances/1.0/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  /home/username/MultiMC/install/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/username/MultiMC/install/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/username/MultiMC/install/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/username/MultiMC/install/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/username/MultiMC/install/libraries/com/mojang/minecraft/1.0/minecraft-1.0-client.jar

Native libraries:
  /home/username/MultiMC/install/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/username/MultiMC/install/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-javaagent:/home/username/MultiMC/install/injectors/authlib-injector-1.1.40.jar=http://localhost:35175, -Xms204m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 16105


[authlib-injector] [INFO] Logging file: /home/username/MultiMC/install/instances/1.0/.minecraft/authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.40
[authlib-injector] [INFO] Authentication server: http://localhost:35175
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

Launching with applet wrapper...
27 achievements
174 recipes
Setting user: <ACCESS TOKEN>, token:<ACCESS TOKEN>:<PROFILE ID>
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: /home/username/MultiMC/install/instances/1.0/natives/liblwjgl.so: /home/username/MultiMC/install/instances/1.0/natives/liblwjgl.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.a(SourceFile:187)
	at net.minecraft.client.Minecraft.run(SourceFile:644)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Samisafool** [comment]
I think that's an arm issue. Try running anything above 1.16.5.

**Comment by Samisafool** [comment]
Anyway you can use latest version of the launcher now

**Comment by glowiak** [comment]
Möjäng does not provide libraries for ARM sadly. Look https://github.com/Botspot/pi-apps/blob/master/apps/Minecraft%20Java/install-32 and https://github.com/Botspot/pi-apps/blob/master/apps/Minecraft%20Java%20MultiMC5/install . They have a solution I think

**Comment by Sebastian-byte** [comment]
Not officially supported by upstream, so neither we do support it.
