### ISSUE TITLE
Ely.By Failed to Fetch Metadata

### ISSUE THREAD

**Issue by Qpac-x** [AfoninZ/UltimMC#134]
### Operating System

Linux

### Description of bug

[authlib-injector] [ERROR] Failed to fetch metadata: java.io.IOException: Server returned HTTP response code: 504 for URL: https://ely.by

### Steps to reproduce

i dont know i just tried playing a curseforge modpack crucial 2 to be exact

### Suspected cause

something to do with ely.by injector

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
Unable to reproduce, likely the website was down temporarily?
