### ISSUE TITLE
Only offline Mode and/or nothing

### ISSUE THREAD

**Issue by DanLP6** [AfoninZ/UltimMC#141]
### Operating System

Windows

### Description of bug

If I try to launch vanilla versions with the latest version and ely.by it crashes. if i run it in offline mode it works (more or less fine)
But if I install a modpack (I used create live) it crashes (online/offline mode)
Hopfully you can fix this... (btw yes I had enough ram)

### Steps to reproduce

1st
- Install instance (in my case 1.12.2)
- run it 
- create a world
- ISSUE
- go to settings
- press start in offline mode
- everything works

2nd
- Install modpack
- run it
- create a world
- ISSUE
- go to settings
- press start in offline mode
- create another world
- ISSUE

### Suspected cause

1st
- The mod ely.by brings it in the normal intstance to crash
2nd
- I have no idea

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Try the latest version

**Comment by Sebastian-byte** [comment]
Unable to reproduce, try newer versions.
