### ISSUE TITLE
Windows clients on local account fail to connect to multiplayer servers with "Connection Lost"

### ISSUE THREAD

**Issue by unsubtract** [AfoninZ/UltimMC#142]
### Operating System

Windows

### Description of bug

Attempting to join a cracked multiplayer server with a Windows client immediately disconnects with the message "Connection Lost" and no further text.

Logs on the server read `[username] joined the game` followed by `[username] lost connection: Disconnected` immediately after, and the join/leave messages are present in chat.

### Steps to reproduce

1. Start an instance with a Local account
2. Attempt to join a cracked multiplayer server

### Suspected cause

The only cause I suspect is that the current CI Windows builds are faulty, as the exact same account and instance on a Linux client is fully-functional.
This bug is reproduced regardless of username on a vanilla client.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by unsubtract** [comment]
This also happens on LAN worlds, both when an authenticated account connects to a local account's world and vice-verca.

**Comment by Sebastian-byte** [comment]
Unable to reproduce, try using a newer version.
