### ISSUE TITLE
Can't connect to Ely.by

### ISSUE THREAD

**Issue by Ka1dz0** [AfoninZ/UltimMC#148]
### Operating System

Windows

### Description of bug

When I try to log in to Ely.By - displays an error "An error occurred while getting the Minecraft Java profile.

### Steps to reproduce

When I try to log in to Ely.By - displays an error "An error occurred while getting the Minecraft Java profile.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
Unable to reproduce, likely fixed in a newer version.
