### ISSUE TITLE
Can't add an account

### ISSUE THREAD

**Issue by Mazinhom** [AfoninZ/UltimMC#149]
### Operating System

Windows

### Description of bug

(I am new to this so please forgive me if I am missing somehing obvious)

Keep getting this error when trying to add a local/ely.by account: "Minecraft Java profile acquisition failed".

### Steps to reproduce

Keep getting this error when trying to add a local/ely.by account: "Minecraft Java profile acquisition failed".

### Suspected cause

No idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Mazinhom** [comment]
> Duplicate of #148

Different error message

**Comment by LeRenner** [comment]
I have exactly the same problem. Here's the log of when I try to log in with a local account:

```
   14.371 D LOOKUP AUTH_PROVIDER "dummy"                                                                                   14.372 D Task "MojangLogin(0x6542db8)" starting for the first time                                                      14.372 D AuthFlow: "Logging in with Mojang account."                                                                    14.373 D Task "Yggdrasil(0x6614628)" starting for the first time                                                        14.689 D Read  423  bytes                                                                                               14.689 D Processing request                                                                                             14.690 D Processing authentication response.                                                                            14.690 D Getting access token.                                                                                          14.691 D Finished reading authentication response.                                                                      14.691 D Task "Yggdrasil(0x6614628)" succeeded                                                                          14.691 D AuthFlow: "Fetching the Minecraft profile."                                                                    15.320 W AuthRequest::onRequestError: Error 204                                                                         15.320 W AuthRequest::onRequestError: Error string:  "Host requires authentication"                                     15.320 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"                                                    15.321 C Task "MojangLogin(0x6542db8)" failed:  "Minecraft Java profile acquisition failed." 
```

**Comment by Mazinhom** [comment]
> I have exactly the same problem. Here's the log of when I try to log in with a local account:
> 
> ```
>    11.247 D LOOKUP AUTH_PROVIDER "dummy"
>    11.247 D Task "MojangLogin(0x4a062f0)" starting for the first time
>    11.247 D AuthFlow: "Logging in with Mojang account."
>    11.247 D Task "Yggdrasil(0x636b640)" starting for the first time
>    11.555 D Read  424  bytes
>    11.556 D Processing request
>    11.556 D Processing authentication response.
>    11.556 D Getting access token.
>    11.556 D Finished reading authentication response.
>    11.556 D Task "Yggdrasil(0x636b640)" succeeded
>    11.557 D AuthFlow: "Fetching the Minecraft profile."
>    12.173 W AuthRequest::onRequestError: Error 204
>    12.174 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
>    12.174 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
>    12.174 C Task "MojangLogin(0x4a062f0)" failed:  "Minecraft Java profile acquisition failed."
> ```

Just checked mine and it's the same.

**Comment by objectiveassignment** [comment]
> 

same issue here too, shows the same in log

**Comment by jznav9ex** [comment]
same issue, same log

**Comment by Dlanis** [comment]
same issue too

**Comment by shibahaczix** [comment]
move files from old launcher [all] to the new and files that all ready are there skip them i did it and i fixed it so easly
lol the new version just has missing files

**Comment by shibahaczix** [comment]
also its not an issue cus they just justed normal multimc and didnt change anything just changed the start file

**Comment by shibahaczix** [comment]
> move files from old launcher [all] to the new launcher and files that all ready are there skip them i did it and i fixed it so easy
> 
> PS: i know that it works in old version there wasnt any forge 1.17.1 when i did this i haved forge 1.17.1 **was this helpfull?**

THIS is not true it buged ! sorry

**Comment by Lucas559-noob** [comment]
a temporary fix for this is using a old exe, https://drive.google.com/file/d/1KL4wLFiQu5IFaoc461alzfEsF52MLxG8/view?usp=sharing [VT  ](https://www.virustotal.com/gui/file/f28257f3d70fd0b4752994a4a27992964910bc6ff6d6fb70cd438cd09b1d5d71)

**Comment by Mazinhom** [comment]
> a temporary fix for this is using a old exe, https://drive.google.com/file/d/1KL4wLFiQu5IFaoc461alzfEsF52MLxG8/view?usp=sharing [VT ](https://www.virustotal.com/gui/file/f28257f3d70fd0b4752994a4a27992964910bc6ff6d6fb70cd438cd09b1d5d71)

Works for now. I hope they do fix this tho in a new version.

**Comment by Samisafool** [comment]
This IS fixed in a new version. Download the latest.

**Comment by Dlanis** [comment]
For me work too.

**Comment by cybercity-com** [comment]
This is still a problem

**Comment by Samisafool** [comment]
Ok this is fixed in the newest one, atleast on linux it works
