### ISSUE TITLE
Pre-built binaries for older MacOs

### ISSUE THREAD

**Issue by srbismuto** [AfoninZ/UltimMC#153]
### Role

Need to launch multimc in Older versions of MacOS

### Suggestion

make a option to download pre-built binaries for MacOs older than 10.13

### Benefit

able to play multimc cracked in older versions of MacOs

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by AndreVuillemot** [comment]
Unfortunately, GitHub Actions doesn't provide ancient Mac OS version, support so no.
See here https://github.com/actions/virtual-environments#available-environments
