### ISSUE TITLE
can't add ely.by account.

### ISSUE THREAD

**Issue by son123cats** [AfoninZ/UltimMC#159]
### Description of bug

when i add ely.by account ultimmc is show the email like local account.

### Steps to reproduce

fix it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
I'm sorry what? Ely.by needs an email and a password to use. If you haven't registered yet, do so [here](https://ely.by).

**Comment by Ka1dz0** [comment]
> Извините, что? Для использования Ely.by требуется электронная почта и пароль. Если вы еще не зарегистрировались, сделайте это [здесь](https://ely.by) .

Dude.... When trying to log in through Ely.by, Mail is displayed instead of a login, and instead of Nick in the game is shown mail ... That is, there are no skins and other things, as in the game itself your name is mail

**Comment by Ivan831** [comment]
The same thing when you go through Ely.by Mail is displayed instead of login. And minecraft does not work with mods when it crashes. Before that, everything worked.

**Comment by cybercity-com** [comment]
It's the same with me

**Comment by fjdhj** [comment]
Try to use your Username instead of your Mail when you add your Ely.by account.

**Comment by Sebastian-byte** [comment]
Login with your username instead of your email.
