### ISSUE TITLE
Bug with Ely.By log in.

### ISSUE THREAD

**Issue by literally-Zak** [AfoninZ/UltimMC#160]
### Operating System

Windows, macOS, Linux

### Description of bug

When trying to log in with an **Ely.By** account, it shows the e-mail address instead of the Username.

![elyby-login-troube1 30 2022](https://user-images.githubusercontent.com/98234074/151711513-93ac4473-2e0a-49f0-bb03-14df63b83b47.png)

### Steps to reproduce:

_- Open UltimMC_
_- Log in with Ely.By account._

**Comment by Ivan831** [comment]
Also such stuff. Another assembly with mods does not start gives an error code of 1.

**Comment by Githux1** [comment]
Experiencing same issue here

**Comment by Githux1** [comment]
I browsed almost all issues regarding ely by and this solves the issue.

https://github.com/AfoninZ/MultiMC5-Cracked/issues/149#issuecomment-1019708115

Reverting to an older version finally fixed the ElyBy authentication issue. My skin and username showed up properly both in the menu and in-game. The new version screws something up I guess.

**Comment by Lucas559-noob** [comment]
Well, not sure if this only affect the launcher, but you can change the username from accounts.json

**Comment by TheBeeBoi** [comment]
Lul

**Comment by cybercity-com** [comment]
This is still a problem

**Comment by Sebastian-byte** [comment]
Login with your username instead of your email.
