### ISSUE TITLE
Error building on NixOS

### ISSUE THREAD

**Issue by wrkzk** [AfoninZ/UltimMC#165]
### Operating System

Linux (NixOS)

### Description of bug

Everything seems to build fine, until it gets to the install phase. I then get the error below. As I mentioned earlier, I am on NixOS if that matters.
`install: cannot stat '../launcher/resources/multimc/scalable/multimc.svg': No such file or directory`

### Steps to reproduce

Build the project.

### Suspected cause

Well it seems that multimc.svg is missing, but I looked on both the official repo and the cracked version and could not find this file anywhere, so I really have no idea.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
NixOS isn't officially supported by the upstream, so neither we do.

**Comment by Samisafool** [comment]
NixOS is just another linux. @wrkzk retry with latest code
