### ISSUE TITLE
Game won't start when logged in to Ely.by

### ISSUE THREAD

**Issue by McMeanBean** [AfoninZ/UltimMC#167]
### Operating System

Windows

### Description of bug

Everything works fine when I play with a local account, but when I attempt to start an an instance of Minecraft while logged in to my Ely.by account I get the following error message:

[authlib-injector] [ERROR] Failed to fetch metadata: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Process exited with code 1.
 
Tried reinstalling but that didn't seem to do anything, so I'm a little stumped.

### Steps to reproduce

1. Open UltimMC
2. Log in to Ely.by account
3. Start an instance of Minecraft

### Suspected cause

I played with a local account for a bit first so maybe that caused issues with the Ely.by account but I doubt it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by retapic** [comment]
Just like me.
I have the following system:
**OS** - Win 10 Pro 21H2 _64-bit_
**CPU** - AMD Ryzen 7 1700
**GPU** - ASUS GeForce 8400 GS _(256MB; DDR2)_
**RAM** - 16 GB _DDR4_

What do you have?

**Comment by Sebastian-byte** [comment]
Unable to reproduce, no follow up, maybe try updating?
