### ISSUE TITLE
Ely.by login uses email as username instead of ely.by username

### ISSUE THREAD

**Issue by mrcorpz** [AfoninZ/UltimMC#168]
### Operating System

Windows

### Description of bug

If logged in with ely.by, your email will be your username. This is game breaking because server only allow username to be 16 characters long and will not let you join.

### Steps to reproduce

1. log in with ely.by
2. try join a multiplayer server

### Suspected cause

Maybe something is wrong with ely.by api or it was implemented incorectly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheBeeBoi** [comment]
Happened to me too.

**Comment by Lucas559-noob** [comment]
also skin don't work, because looks like on a attempt to remove the verification, they removed the connection, so it just... can't connect to ely.by

**Comment by taufik-ridwan** [comment]
i have the same issue too

**Comment by 1NF1N173-V01D** [comment]
I have the same issue as well ely.by skins just dont work

**Comment by cybercity-com** [comment]
me too

**Comment by fjdhj** [comment]
Try to create a new ely.by account with your username and not your email

**Comment by RafeeDaBoy** [comment]
> i have the same issue too

Me too 
![image](https://user-images.githubusercontent.com/69535896/155850691-95f9397b-6ddc-42c8-b9a6-96f501d8dcba.png)

**Comment by 1NF1N173-V01D** [comment]
> 

You need an email to create a Ely.by account and there is also the issue of the skin not showing after we log into ely.by

**Comment by 1NF1N173-V01D** [comment]
> Try to create a new ely.by account with your username and not your email
You need an email to create a Ely.by account and then there is also the issue of the skin not showing after we log into ely.by

**Comment by 7sergi9** [comment]
Has anyone managed to fix this?
the skins are not working.

**Comment by RafeeDaBoy** [comment]
No, unfortunately I'm still having the same issue.

**Comment by Panderine** [comment]
The issue is in ely.by no new account is able to provide the correct uuid to your server if it's in online mode. If ultimMC had previously cached your skin and account from ely.by then you have no issues, but if you create a new account or change your skin in  doesn't work anymore.

**Comment by Yimellovzski** [comment]
I was able to log in using my username (in the email box) and password, maybe try that?

**Comment by mrcorpz** [comment]
> I was able to log in using my username (in the email box) and password, maybe try that?
That does seem to work for me too

**Comment by Sebastian-byte** [comment]
Clone of #160
