### ISSUE TITLE
skin

### ISSUE THREAD

**Issue by cybercity-com** [AfoninZ/UltimMC#169]
### Role

ely.by

### Suggestion

How do I show the skin?

### Benefit

I need

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I logged in from ely.by, but my skin did not show me what to do?

**Comment by RafeeDaBoy** [comment]
I'm having the same issue. I have selected a skin in el.by and logged into my account from the launcher, but the skin doesn't seem to show up
![image](https://user-images.githubusercontent.com/69535896/155850565-02535787-4062-41ef-81b3-6d29bcd5a91d.png)

**Comment by Sebastian-byte** [comment]
This is likely fixed if you login with your username instead of email, I'll look further into the skins problem.
