### ISSUE TITLE
Ely.by skins are not working 

### ISSUE THREAD

**Issue by 7sergi9** [AfoninZ/UltimMC#172]
### Description of bug

ely.by skins are not working 

### Steps to reproduce

Logging in with an ely.by account is useless, as the skins are not shown. 

### Suspected cause

Launcher bug 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Marcelo20XX** [comment]
ely.by is working. I have skins showing on my game. You need to download ely.by's authlib and replace the UltimMC one. Directions are on Ely.by website

**Comment by 7sergi9** [comment]
> ely.by is working. I have skins showing on my game. You need to download ely.by's authlib and replace the UltimMC one, if the version's don't match just rename it to the UltimMC one, it will still work. Directions are on Ely.by website... and also you need to start the game in offline or else MineCraft will download and replace the authlib again...

I have done this and the skins are still not working, can you upload your folder?

**Comment by Marcelo20XX** [comment]
you only need to download and rename the downloaded authlib from ely.by to "authlib-2.3.31.jar" and put it inside "yourgamefolder\libraries\com\mojang\authlib\2.3.31\"

**Comment by TroxxyTheSuicidalDuck** [comment]
> you only need to download and rename the downloaded authlib from ely.by to "authlib-2.3.31.jar" and put it inside "yourgamefolder\libraries\com\mojang\authlib\2.3.31"
> 
> After that you need to create a new account selecting ely.by as an option and just login with your user and pass from the account you registered on ely.by. Launch in offline mode and you are set...

Hey! i did everything as instructed, but for some reason UltimMC just crashes after the edit with an Error Code -1
it happends only when i try to launch it in offline mode
otherwise, the newly added authlib just gets replaced with the old one
any thoughs on why is that so?

thanks in advance!

**Comment by tyrael93** [comment]
I was wracking my head over this and I seem to have found a solution that works perfectly, at least for 1.7.
![1](https://user-images.githubusercontent.com/5557920/165715881-ad5cde14-c955-4496-b6a2-f57cd0a4e158.png)

I suggest anyone who is currently working on this issue to give it a look, in case it might be of any help, so it gets fixed in mainline. It seems to be a tlauncher fix, which is the main ely.by supported launcher, but it works for UMC too.
https://www.curseforge.com/minecraft/mc-mods/tl-skin-and-cape-mod

**Comment by Sebastian-byte** [comment]
This is likely fixed if you login with your username instead of email, I'll look further into the skins problem,

**Comment by N3onKn1ght** [comment]
This is not working if you log in with ely.by nickame, the authlib was imported, I launched offline, and it is not working.
