### ISSUE TITLE
Possible ManyMC fork, it is native fork of MultiMC

### ISSUE THREAD

**Issue by imabhaysutar** [AfoninZ/UltimMC#173]
### Role

I play

### Suggestion

Cracked fork for ManyMC

### Benefit

Native app, means less hassle to setup on apple silicon Macs.. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by AndreVuillemot** [comment]
You could try to port a few PRs that guy made for this project.

**Comment by AndreVuillemot** [comment]
https://github.com/AfoninZ/MultiMC5-Cracked/pull/31

**Comment by AndreVuillemot** [comment]
I have no idea if it works, but I have made a fork here
https://github.com/AndreVuillemot/ManyMC

If it works let me know about that, first time porting.

**Comment by imabhaysutar** [comment]
won't build

**Comment by AndreVuillemot** [comment]
> won't build

Saying "won't build" doesn't help me.

Post logs of build.

**Comment by imabhaysutar** [comment]
'AuthServer.h' file not found

**Comment by niklausthetitan** [comment]
Changing the line:
`set(Launcher_META_URL "https://meta.multimc.org/v1/" CACHE STRING "URL to fetch Launcher's meta files from.")`
to:
`set(Launcher_META_URL "https://minecraftmachina.github.io/meta-multimc-arm64/" CACHE STRING "URL to fetch Launcher's meta files from.")`
in CMakeLists.txt is enough to make MultiMC download the arm64 libraries provided by ManyMC's author.

After changing that you can build everything and it will just work, tested on my M1 MBA.

**Comment by Sebastian-byte** [comment]
Support for Apple Silicon should be implemented in the upstream, it doesn't support it yet, so we don't either.
