### ISSUE TITLE
Outdated Build Instructions

### ISSUE THREAD

**Issue by Marcelo20XX** [AfoninZ/UltimMC#174]
### Operating System

Windows

### Description of bug

Unable to build the Launcher from source by following the Build.md instructions. Downloaded all the required software and dependencies and no dice...

### Steps to reproduce

Try to compile the source

### Suspected cause

Outdated instructions

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
This is a problem that should be solved in the upstream, in the meanwhile, you can follow the "instructions" in the GitHub Actions script.
