### ISSUE TITLE
You do not have permission to open the application

### ISSUE THREAD

**Issue by CodeGenStudio** [AfoninZ/UltimMC#175]
Hey so I downloaded MultiMC5 cracked/ultimMC from this [link](https://nightly.link/AfoninZ/MultiMC5-Cracked/workflows/main/develop). When I download the one for macOS and launch the UltimMC.app (even tried control click > open aka rightclick then open) it gives me this error:
![ss](https://user-images.githubusercontent.com/81819789/160493942-a83f7831-6363-499a-8456-332622aee3db.png)

Any help would be appreciated. Thanks in advance.

EDIT: I forgot to mention I did the chmod +x UltimMC in terminal but still the error. Tested launching the app before running the command and after running the command.

**Comment by LordXerus** [comment]
Does this help?
https://apple.stackexchange.com/questions/408752/the-message-you-do-not-have-permission-to-open-the-application-is-shown-when-t
