### ISSUE TITLE
UltimMC Crashes After Replacing AuthLib With the one from ely.by

### ISSUE THREAD

**Issue by TroxxyTheSuicidalDuck** [AfoninZ/UltimMC#177]
### Operating System

Windows

### Description of bug

UltimMC Crashes After Replacing AuthLib With the one from ely.by and going into offline mode

I Loggen in using ely.by, but my skin wasnt showing up
After that, i've found a solution ( #172 ) that didnt work for me.. Since after replacing AuthLib in:
 ( C:\UltimMC\UltimMC\libraries\com\mojang\authlib ) 
With the one downloaded from ely.by, and launching offline mode, the game crashes with this; https://paste.ee/p/wN1DA error log

### Steps to reproduce

1. Download 1.18 AuthLib from Ely.by
2. extract the .jar file within the downloaded archive
3. replace, or delete the same .jar file by the path: C:\UltimMC\UltimMC\libraries\com\mojang\authlib\3.3.39   with the one downloaded earlier,changing its name as to match the original one, that was deleted seconds ago
4. try to launch an instance in offline
5.  get an error message

### Suspected cause

not a clue

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ekiniko12** [comment]
Same thing happens to me as well.

**Comment by Samisafool** [comment]
Try replacing `C:/UltimMC/UltimMC/injectors/authlib-injector-1.1.42.jar` too

**Comment by TroxxyTheSuicidalDuck** [comment]
> Try replacing `C:/UltimMC/UltimMC/injectors/authlib-injector-1.1.42.jar` too

i doubt it will work..
there is no authinjector on ely.by website to download and use as a replacement
if youre talking about authlib.jar, renaming it into authlib-injector.jar, that too probably wont work, since these two files serve different functions, and have different file weight (authlib- 102kb, injector- 310kb)
so i doubt that one file could replace those 2, since they have a different purpose

**Comment by Samisafool** [comment]
injector https://github.com/yushijinhun/authlib-injector/releases/tag/v1.1.42

**Comment by TroxxyTheSuicidalDuck** [comment]
> injector https://github.com/yushijinhun/authlib-injector/releases/tag/v1.1.42

replaced original injector with the one in the link, still crashes

**Comment by Samisafool** [comment]
Argh, dependency hell...

**Comment by Panderine** [comment]
injector is download automagically. You need to add your account with an old version of ultimc and then you can use lastest version with your already added account.

**Comment by TroxxyTheSuicidalDuck** [comment]
> 

thanks!
that might actually work, but i cant seem to find any older versions here that are already compiled
i've found source code for 1.6.11 and older, but im not sure what to do with them.. might figure out a bit later
Is there any link for the older versions, or do i need to somehow compile it from the surce code?

**Comment by Granth9923** [comment]
I got the solution, use java 8 and minecraft wont crash. Atleast worked for me, you can use java 8+ for unmodded versions.

**Comment by Sebastian-byte** [comment]
You can also try login in with your username instead of email.
