### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by nTanikaze** [AfoninZ/UltimMC#178]
### Description of bug

the link on readme to download its broken

### Steps to reproduce

link broken

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Qpac-x** [comment]
the link is fine
https://nightly.link/AfoninZ/UltimMC/workflows/main/develop

**Comment by Samisafool** [comment]
It was updated recently
