### ISSUE TITLE
Mods from the launcher

### ISSUE THREAD

**Issue by Mr-Squeaky-Voice** [AfoninZ/UltimMC#181]
### Role

I play Modded Minecraft

### Suggestion

Add a feature to be able to add mods into a modpack from the launcher instead of downloading it from curseforge and adding it to multimc modpack

### Benefit

So it is easier to add mods that you would like in a modpack that doesn't already have it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Instead of downloading mods from curseforge and adding them to a modpack, there should be a section to choose any mod from curseforge to add to a modpack like the section for selecting a modpack.

**Comment by Mr-Squeaky-Voice** [comment]
Also, how do I update the launcher?

**Comment by Sebastian-byte** [comment]
Request this feature to the upstream, although I'm pretty sure that's already possible, to update there are instructions in the readme.
