### ISSUE TITLE
Any way I can launch the game in offline mode automatically?

### ISSUE THREAD

**Issue by Yimellovzski** [AfoninZ/UltimMC#182]
### Role

I play minecraft all the time and I get worried I accidentally launch the game in online mode, and override the authlib jar

### Suggestion

Maybe I could get any help in setting up a custom argument for that

### Benefit

to avoid misclicks and launching the game online mode

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Sebastian-byte** [comment]
Launching the game in online mode won't do anything, this isn't a problem.
