### ISSUE TITLE
Explain

### ISSUE THREAD

**Issue by EliteFDGod** [AfoninZ/UltimMC#183]
### Role

I play moded minecraft

### Suggestion

Can anyone explain how i start the launcher now?

### Benefit

By this you get more users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Can anyone explain how i start the launcher now? I downloaded it 3 weeks ago and it worked, but yesterday i reinstalled windows and I see no launcher at all. I'm not a coding guy so if you don't mind make an explanation please.

**Comment by Samisafool** [comment]
You reinstalled windows, now reinstall the launcher.

Just install it again.

**Comment by EliteFDGod** [comment]
But where? when i download these files i used to see a launcher.exe now i cant find it, or im downloading wrong files? Then give me a link or an instruction pls

**Comment by Samisafool** [comment]
install from https://nightly.link/AfoninZ/UltimMC/workflows/main/develop, the windows version. then unzip it and click the exe.

**Comment by Samisafool** [comment]
the name is ultimmc.exe now

**Comment by EliteFDGod** [comment]
I downloaded it, unziped it and the only similira thing i can find in the MacOs folder is UltimMc.file, do i have a problem not seeing an exe or what can i do?

**Comment by EliteFDGod** [comment]
PFFFFF daaaamn kill me i downloaded the osx64 thinking its windows 64 bit but i think is for mac now  :)))) now i downloaded the x32 zip and i found it, thank you very much, btw post the download link somewhere in the main page so stupid people like me can see it and not bothering you, thank you once again :D

**Comment by EliteFDGod** [comment]
If you are here can u still help pls, i got this error:

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Exiting with -1
Process exited with code -1.

**Comment by EliteFDGod** [comment]
If i try to add an ely.by account i get this: Mojang user authentication ended with a network error.

**Comment by EliteFDGod** [comment]
> > btw post the download link bigger somewhere in the main page so stupid people like me can see it and not bothering you
> 
> https://github.com/AfoninZ/UltimMC#pre-built-binaries
> 
> > Here is the full log https://paste.ee/p/O0iZw
> 
> Try to use a newer game version

Im probably using the latest infinity pack, cause there is only 1, something like 3.1.idk

**Comment by Samisafool** [comment]
I mean like 1.18 or 1.12

**Comment by EliteFDGod** [comment]
Infinity evolved can be played just in mc1. 7.10
I fixet it now, downloaded a few types of java, smt is not suporting java version above 1.8.0

**Comment by theamazing0** [comment]
I'm _pretty_ sure

Minecraft Until Version 1.17 uses Java 8
Minecraft 1.17 uses Java 16
Minecraft 1.18  uses Java 18
