### ISSUE TITLE
There is a problem with the Ely.by account.

### ISSUE THREAD

**Issue by Ivan831** [AfoninZ/UltimMC#184]
### Operating System

Windows

### Description of bug

I go to the Ely.by account, instead of a nickname it shows mail, and there is no skin.

### Steps to reproduce

![Снимок экрана (1)](https://user-images.githubusercontent.com/32361356/164890269-7efdce52-5c08-444f-ad18-7066b10f07a8.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
Login your username instead of your email.
