### ISSUE TITLE
Trojan detected in VirusTotal? 

### ISSUE THREAD

**Issue by seannn9** [AfoninZ/UltimMC#187]
Here's the link to the file scan
https://www.virustotal.com/gui/file/f8a72ebe23da0bd890b274ae467bb4ab1ac1d1c005112d10e4e05a2c833a9209

I'm pretty paranoid with viruses so I'm a bit worried to execute the exe

**Comment by Samisafool** [comment]
Yeah that's a false positive. All but one detected it as safe.

**Comment by seannn9** [comment]
Yeah thought so too. Just had to make sure. Thanks!

**Comment by milena-kos** [comment]
you can close issue if it is resolved

**Comment by Sebastian-byte** [comment]
Pro-Tip: If only 1 or 2 antiviruses detect a file in VirusTotal it most certainly means it's a false positive.

**Comment by zackfall** [comment]
Pro-Tip: It doesn't matter if it's just one or two warnings, be aware of any suspicious thing you see and investigate before using something
