### ISSUE TITLE
multimc error i need a official minecraft account to play on a older version then 1.18.2 

### ISSUE THREAD

**Issue by eskander12** [AfoninZ/UltimMC#189]
### Operating System

_linux_

### Description of bug

![Screenshot from 2022-04-30 15-58-35](https://user-images.githubusercontent.com/90553902/166108783-7cbc2e3e-94ea-4cc4-947d-5f979aa9233b.png)

![Screenshot from 2022-04-30 15-58-11](https://user-images.githubusercontent.com/90553902/166108826-e889044b-3038-496b-ab1e-898887e4c99a.png)
when i click 'download all'  the error below shows up 
                                          

![Screenshot from 2022-04-30 15-58-54](https://user-images.githubusercontent.com/90553902/166108847-adcdcdb8-3745-4d7b-a9ed-3c29f7adf551.png)

now i can only play on 1.18.2

### Steps to reproduce

i dont know

### Suspected cause

no idea 

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by marek26340** [comment]
It is not clear from your description of the issue if you've RTFM or not. 
Have you added a fake account in the settings menu according to the instructions?
Everything works fine for me.

**Comment by Sebastian-byte** [comment]
Unable to reproduce.
