### ISSUE TITLE
[Bug] Unable to play multiplayer "Disconnected"

### ISSUE THREAD

**Issue by ANDREI12333** [AfoninZ/UltimMC#190]
### Operating System

Windows

### Description of bug

I expected to be connected to the server.

### Steps to reproduce

* Create a instance
* Join any server
* See error

### Suspected cause

The join packet too big (A error with a packet being 64 bytes instead of 32 bytes showed up first time i tried joining a server using UltimMC

**Disconnected:**
![image](https://user-images.githubusercontent.com/72381315/166343526-31129d95-02af-4950-a5c5-ce894465a63d.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ANDREI12333** [comment]
**Update:**
I have tried these two options, Didn't work
![image](https://user-images.githubusercontent.com/72381315/166343778-17f26c8b-028c-46ee-9c6c-ec1b63312385.png)

**Comment by Samisafool** [comment]
Send logs

**Comment by ANDREI12333** [comment]
**Update:**
There's a simple way to fix this, When logging in with Ely.by use your username not your email.
