### ISSUE TITLE
Ely.by skin not showing

### ISSUE THREAD

**Issue by BlastingCreeper** [AfoninZ/UltimMC#192]
### Operating System

Windows

### Description of bug

I have logged onto UltimMC with my ely.by account but the skin is not visible. Other ely.by users skins are not showing, but people using MClauncher(official ely.by launcher) can see my skin.

### Steps to reproduce

(I have no idea what to put here)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BlastingCreeper** [comment]
i fixed it nm

**Comment by liminalityyy** [comment]
> i fixed it nm

could you explain the fix since i sorta need it as well
