### ISSUE TITLE
I cant see my skin after logging in with ely.by

### ISSUE THREAD

**Issue by Granth9923** [AfoninZ/UltimMC#195]
### Operating System

Windows

### Description of bug

I cant see my skin even after logging in with ely.by, I have tried reinstalling the launcher several times but the issue still persists.

### Steps to reproduce

Any solutions may be helpfull I guess

### Suspected cause

i d k

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
See #184, #177, #168, #172

Stop making duplicate issues ffs

**Comment by Granth9923** [comment]
Ok thanks and sorry for duplicate issue!
