### ISSUE TITLE
not a suggestion but a question

### ISSUE THREAD

**Issue by derplordofdeath** [AfoninZ/UltimMC#196]
### Role

question

### Suggestion

question *let me play offline without using a token*

### Benefit

question

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

if i download this fork will i be able to play minecraft ofline/online without using a token? for instance i own minecraft i bought it and occasionally i dont play for a month or two so when i go to play it again it says my token wont work and i have to be connected to the internet which is a problem because sometimes my internet goes out for weeks and i dont wanna be deprived of a game i paid for so will this remedy that problem? aka will this let me play my game whenever i want

![Screenshot (51)](https://user-images.githubusercontent.com/75479104/168563043-696813fa-8446-48a5-acd8-f7a9a15090aa.png)
?

*example of this happening to me for the 7th time* ^

**Comment by Samisafool** [comment]
Use https://multimc.org instead of UltimMC.

**Comment by derplordofdeath** [comment]
thats what i use already...

**Comment by Samisafool** [comment]
So report it at https://github.com/MultiMC/launcher

**Comment by derplordofdeath** [comment]
so the token thing is on microsofts side of the fence so unless i pirate minecraft i cant play offline even though i own it... thats fucking wild
