### ISSUE TITLE
CurseMeta will go down permantly soon.

### ISSUE THREAD

**Issue by dries007** [AfoninZ/UltimMC#197]
I don't know if you guys follow the upstream at all, but I thought I'd leave a note here as well.

See MultiMC/Launcher#4690

**Comment by Sebastian-byte** [comment]
Thanks for thinking about us too! I just merged with upstream and the patch should be here too, now we only have to fix the build (again... 😅)

**Comment by Samisafool** [comment]
> we only have to fix the build (again... 😅)

See #200
