### ISSUE TITLE
Adding the PolyMC patch that fixes adding modpacks from Curseforge (since cursemeta is dead)

### ISSUE THREAD

**Issue by tariqaq** [AfoninZ/UltimMC#199]
### Role

I use it for modpacks and I liked how easy it was to add modpacks from curseforge search function, that is untill it stopped working due to cursemeta going dead.

### Suggestion

I would like to have it fixed by possibly adding the patch from PolyMC that fixes adding modpacks from Curseforge.

### Benefit

This is so that modpacks can be added as usual again.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by xanobus** [comment]
Make a patch version based on UltimMC

**Comment by Sebastian-byte** [comment]
If I understood correctly, this should be implemented in the upstream.
