### ISSUE TITLE
Ely.by nickname

### ISSUE THREAD

**Issue by iTzArcheeerR** [AfoninZ/UltimMC#204]
### Description of bug

When I sign in with ely.by, my email appears as my in-game nickname

(I already changed my name on Ely.by)

### Steps to reproduce

Log in with ely.by and open the game, create a new world and send something in the chat

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ka1dz0** [comment]
It's already been done many times. #131 #134 #148 #159 #160 #167 #168 #172 #177 #184 .
The only way to solve this problem is to change the "exe" (**read 149 comments, there threw the exe**) file to the old one, log in to your account, and then return the current "exe"
