### ISSUE TITLE
Can't download modpacks from curseforge website

### ISSUE THREAD

**Issue by Mr-Squeaky-Voice** [AfoninZ/UltimMC#206]
### Operating System

Windows

### Description of bug

Downloading any modpack from curseforge doesn't work even if its from a .zip file or a link to the download.

Also, will you ever be able to download curseforge modpacks directly from UltimMC again?

### Steps to reproduce

download a modpack from the curseforge website, then install it through UltimMC. It will give you an error.

### Suspected cause

Curseforge removing their modpacks from 3rd party apps.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
This is a problem that's also happening in the upstream and related to the curseforge API, importing and downloading is broken
```
For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
```
As soon it's solved in the upstream, it will be fixed here too.
