### ISSUE TITLE
Can't play on LAN [Windows 10]

### ISSUE THREAD

**Issue by anonimo4git** [AfoninZ/UltimMC#211]
### Operating System

Windows

### Description of bug

When i try to play with another PC in the same network it always fails with "Disconnected", both computers are running Windows10, the same version of Minecraft without mods, firewall and antivirus completely disabled and using two local accounts with different nicknames.

### Steps to reproduce

On the first computer:
Create a new world in single player 
Press Open to LAN in menu
On the second computer:
Press Multiplayer
The LAN server correctly appears
Join Server
Logging in...
Disconnected

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
Clone of #166

**Comment by anonimo4git** [comment]
Hi Sebastian, it's not a clone because #166 is about playing LAN in the same computer.
Anyway, do you think this issue could be easily solved?
