### ISSUE TITLE
1

### ISSUE THREAD

**Issue by MinecraftNube** [AfoninZ/UltimMC#212]
### Operating System

Windows

### Description of bug

how to fix the launcher so that it can download curse builds?

### Steps to reproduce

no sé cómo arreglarlo.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
It's a problem that's caused by the upstream
-------------------------------------------------
Es un problema causado por el repositorio original.
